import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { RefreshCw, Send } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
type Msg={id:string;user_id:string;order_id:string|null;subject:string;message:string;from_admin:boolean;created_at:string};
type Profile={user_id:string;first_name:string|null;last_name:string|null};
export default function AdminClientMessages(){
 const {toast}=useToast();const [items,setItems]=useState<Msg[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [selected,setSelected]=useState<Msg|null>(null);const [reply,setReply]=useState("");
 const load=async()=>{const {data,error}=await (supabase as any).from("client_messages").select("*").order("created_at",{ascending:false});if(error){toast({title:"Messages clients inaccessibles",description:error.message,variant:"destructive"});return}setItems((data||[]) as Msg[]);const ids=[...new Set((data||[]).map((m:any)=>m.user_id))];if(ids.length){const {data:p}=await (supabase as any).from("profiles").select("user_id,first_name,last_name").in("user_id",ids);setProfiles(Object.fromEntries((p||[]).map((v:any)=>[v.user_id,v])))}};useEffect(()=>{void load()},[]);
 const send=async()=>{if(!selected||!reply.trim())return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await (supabase as any).from("client_messages").insert({user_id:selected.user_id,order_id:selected.order_id,subject:"Re: "+selected.subject,message:reply.trim(),from_admin:true});if(error)toast({title:"Réponse impossible",description:error.message,variant:"destructive"});else{toast({title:"Réponse envoyée"});setReply("");await load()}};
 return <div className="grid gap-6 lg:grid-cols-[1fr_1.2fr]"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Messages clients</CardTitle><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></CardHeader><CardContent className="space-y-2">{!items.length?<p className="py-8 text-center text-sm text-muted-foreground">Aucun échange.</p>:items.map(m=><button key={m.id} onClick={()=>setSelected(m)} className={"w-full rounded-xl border p-3 text-left "+(selected?.id===m.id?"border-primary bg-primary/5":"hover:bg-muted")}><div className="flex justify-between gap-2"><span className="font-medium">{profiles[m.user_id] ? ((profiles[m.user_id].first_name||"")+" "+(profiles[m.user_id].last_name||"")).trim()||"Client" : m.user_id.slice(0,8)}</span><Badge variant={m.from_admin?"secondary":"default"}>{m.from_admin?"Réponse":"Nouveau"}</Badge></div><p className="mt-1 text-sm font-semibold">{m.subject}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{m.message}</p></button>)}</CardContent></Card><Card><CardHeader><CardTitle>{selected?"Répondre au client":"Sélectionnez un échange"}</CardTitle></CardHeader><CardContent>{selected?<div className="space-y-4"><div className="rounded-xl bg-secondary p-4"><p className="text-sm font-semibold">{selected.subject}</p><p className="mt-2 whitespace-pre-wrap text-sm">{selected.message}</p></div><Textarea rows={6} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Votre réponse…"/><Button disabled={!reply.trim()} onClick={()=>void send()}><Send className="mr-2 h-4 w-4"/>Envoyer</Button></div>:<p className="text-sm text-muted-foreground">Les conversations apparaîtront ici.</p>}</CardContent></Card></div>;
}