import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { RefreshCw, Plus, Edit3, Trash2, Save, ExternalLink } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

type Project={id:string;title:string;slug:string;category:string;description:string|null;url:string|null;official_domain:string|null;image_url:string|null;fallback_image_url:string|null;technologies:string[];is_published:boolean;is_featured:boolean;sort_order:number;live_preview_status:string};
const empty={title:"",slug:"",category:"web",description:"",url:"",official_domain:"",image_url:"",fallback_image_url:"",technologies:"",is_published:true,is_featured:false,sort_order:0};
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export default function AdminPortfolio(){
 const {toast}=useToast();const [items,setItems]=useState<Project[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Project|null>(null);const [form,setForm]=useState(empty);const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const {data,error}=await (supabase as any).from("portfolio_projects").select("id,title,slug,category,description,url,official_domain,image_url,fallback_image_url,technologies,is_published,is_featured,sort_order,live_preview_status").order("sort_order",{ascending:true});if(error)toast({title:"Portfolio inaccessible",description:error.message,variant:"destructive"});setItems((data||[]) as Project[]);setLoading(false)};useEffect(()=>{void load()},[]);
 const edit=(p:Project)=>{setEditing(p);setForm({title:p.title,slug:p.slug,category:p.category,description:p.description||"",url:p.url||"",official_domain:p.official_domain||"",image_url:p.image_url||"",fallback_image_url:p.fallback_image_url||"",technologies:(p.technologies||[]).join(", "),is_published:p.is_published,is_featured:p.is_featured,sort_order:p.sort_order});setOpen(true)};
 const reset=()=>{setEditing(null);setForm(empty);setOpen(false)};
 const save=async()=>{if(!form.title.trim()){toast({title:"Titre obligatoire",variant:"destructive"});return}const payload={title:form.title.trim(),slug:form.slug.trim()||slugify(form.title),category:form.category.trim()||"web",description:form.description.trim()||null,url:form.url.trim()||null,official_domain:form.official_domain.trim()||null,image_url:form.image_url.trim()||null,fallback_image_url:form.fallback_image_url.trim()||null,technologies:form.technologies.split(",").map(x=>x.trim()).filter(Boolean),is_published:form.is_published,is_featured:form.is_featured,sort_order:Number(form.sort_order)||0};const q=editing?(supabase as any).from("portfolio_projects").update(payload).eq("id",editing.id):(supabase as any).from("portfolio_projects").insert(payload);const {error}=await q;if(error){toast({title:"Enregistrement impossible",description:error.message,variant:"destructive"});return}toast({title:editing?"Réalisation mise à jour":"Réalisation créée"});reset();await load()};
 const remove=async(p:Project)=>{if(!window.confirm("Supprimer « "+p.title+" » ?"))return;const {error}=await (supabase as any).from("portfolio_projects").delete().eq("id",p.id);if(error)toast({title:"Suppression impossible",description:error.message,variant:"destructive"});else await load()};
 return <div className="space-y-6"><div className="flex flex-col gap-4 rounded-2xl bg-gradient-to-br from-primary to-accent p-6 text-primary-foreground sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] opacity-75">Réalisations</p><h2 className="mt-2 text-2xl font-bold">Portfolio administrable</h2><p className="mt-2 text-sm opacity-80">Les publications alimentent directement le portfolio public et conservent leur domaine officiel et leur fallback.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button><Button onClick={()=>{reset();setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>Ajouter</Button></div></div>
 <Card><CardHeader><CardTitle>{items.length} réalisation(s)</CardTitle></CardHeader><CardContent>{loading?<p className="py-10 text-center text-muted-foreground">Chargement…</p>:<div className="space-y-3">{items.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-xl border p-4 md:flex-row md:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><Badge variant="outline">{p.category}</Badge>{p.is_published&&<Badge>Publié</Badge>}{p.live_preview_status==="live"&&<Badge variant="secondary">LIVE</Badge>}</div><h3 className="mt-1 font-semibold">{p.title}</h3><p className="text-xs text-muted-foreground">{p.official_domain||p.url||"Aucun domaine"}</p></div><div className="flex gap-2">{p.url&&<Button size="sm" variant="outline" asChild><a href={p.url} target="_blank" rel="noreferrer"><ExternalLink className="mr-1 h-4 w-4"/>Visiter</a></Button>}<Button size="sm" variant="outline" onClick={()=>edit(p)}><Edit3 className="mr-1 h-4 w-4"/>Modifier</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={()=>void remove(p)}><Trash2 className="h-4 w-4"/></Button></div></div>)}</div>}</CardContent></Card>
 <Dialog open={open} onOpenChange={v=>!v&&reset()}><DialogContent className="max-w-3xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Modifier la réalisation":"Nouvelle réalisation"}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="text-sm font-medium">Titre</label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><label className="text-sm font-medium">Slug</label><Input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></div><div><label className="text-sm font-medium">Catégorie</label><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div><label className="text-sm font-medium">Domaine officiel</label><Input value={form.official_domain} onChange={e=>setForm({...form,official_domain:e.target.value})}/></div><div><label className="text-sm font-medium">URL</label><Input value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></div><div><label className="text-sm font-medium">Image principale</label><Input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></div><div><label className="text-sm font-medium">Fallback</label><Input value={form.fallback_image_url} onChange={e=>setForm({...form,fallback_image_url:e.target.value})}/></div><div className="sm:col-span-2"><label className="text-sm font-medium">Description</label><Textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="sm:col-span-2"><label className="text-sm font-medium">Technologies, séparées par des virgules</label><Input value={form.technologies} onChange={e=>setForm({...form,technologies:e.target.value})}/></div><div><label className="text-sm font-medium">Ordre</label><Input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></div><div className="flex items-center gap-6 rounded-xl border p-3"><label className="flex items-center gap-2 text-sm"><Switch checked={form.is_published} onCheckedChange={v=>setForm({...form,is_published:v})}/>Publié</label><label className="flex items-center gap-2 text-sm"><Switch checked={form.is_featured} onCheckedChange={v=>setForm({...form,is_featured:v})}/>À la une</label></div></div><DialogFooter><Button variant="outline" onClick={reset}>Annuler</Button><Button onClick={()=>void save()}><Save className="mr-2 h-4 w-4"/>Enregistrer</Button></DialogFooter></DialogContent></Dialog></div>;
}