import { useEffect, useMemo, useState } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import DOMPurify from "dompurify";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Copy, Eye, MessageCircle, Play, CalendarDays, Clock3 } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NotFound from "@/pages/NotFound";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { ArticleJsonLD, BreadcrumbJsonLd, SITE_URL } from "@/components/SeoJsonLd";
import { toast } from "sonner";
import { useLanguage } from "@/hooks/useLanguage";

const parseArray=(v:unknown):string[]=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):typeof v==="string"?(()=>{try{const p=JSON.parse(v);return Array.isArray(p)?p.filter((x):x is string=>typeof x==="string"):[]}catch{return[]}})():[];
const strip=(v="")=>v.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();
const media=(v?:string|null)=>{if(!v)return "";if(/^https?:\/\//i.test(v))return v;if(v.startsWith("/inauguration/")||v.startsWith("/formation/"))return "https://www.agricapital.ci"+v;return v};
const image=(src:string|undefined,alt:string,cls:string)=> <img src={src||"/placeholder.svg"} alt={alt} className={cls} onError={e=>{const i=e.currentTarget;i.onerror=null;i.src="/placeholder.svg"}}/>;
const reading=(v="")=>Math.max(1,Math.ceil(strip(v).split(/\s+/).filter(Boolean).length/220));
type NewsItem={id:string;slug:string;title_fr:string;excerpt_fr?:string|null;content_fr?:string|null;category?:string|null;featured_image?:string|null;images?:unknown;videos?:unknown;author?:string|null;published_at?:string|null;created_at:string;updated_at?:string|null;views_count?:number|null;shares_count?:number|null;[key:string]:any};

export default function ActualiteDetail(){
 const {slug}=useParams<{slug:string}>();const nav=useNavigate();const {language}=useLanguage();const [view,setView]=useState(0);const [shares,setShares]=useState(0);
 const {data:article,isLoading}=useQuery({queryKey:["news-article",slug],enabled:!!slug,queryFn:async()=>{const {data,error}=await (supabase as any).from("news").select("*").eq("slug",slug).eq("is_published",true).maybeSingle();if(data)return data as NewsItem;if(error)return null;const {data:r}=await (supabase as any).from("news_slug_redirects").select("news_id").eq("old_slug",slug).maybeSingle();if(!r?.news_id)return null;const {data:a}=await (supabase as any).from("news").select("*").eq("id",r.news_id).eq("is_published",true).maybeSingle();return a as NewsItem|null},staleTime:0});
 useEffect(()=>window.scrollTo(0,0),[slug]);useEffect(()=>{if(article&&slug&&article.slug!==slug)nav("/actualites/"+article.slug,{replace:true})},[article,slug,nav]);useEffect(()=>{if(!article)return;setView(article.views_count||0);setShares(article.shares_count||0);const k="news-viewed:"+article.id;if(sessionStorage.getItem(k))return;(async()=>{try{sessionStorage.setItem(k,"1");const {data}=await (supabase as any).rpc("increment_news_view",{p_news_id:article.id});if(typeof data==="number")setView(data)}catch{sessionStorage.removeItem(k)}})()},[article]);
 const arr=useMemo(()=>{const a=parseArray(article?.images);return (a.length?a:(article?.featured_image?[article.featured_image]:[])).map(media)},[article]);const vids=article?parseArray(article.videos).map(media):[];const loc=(k:"title"|"excerpt"|"content")=>(article?.[k+"_"+language]||article?.[k+"_fr"]||"").trim();const title=loc("title"),excerpt=loc("excerpt")||strip(loc("content")).slice(0,260),content=loc("content");const url=SITE_URL+"/actualites/"+(article?.slug||slug);const safe=DOMPurify.sanitize(content,{ALLOWED_TAGS:["p","h2","h3","strong","em","br","hr","li","ul","ol","a","blockquote","table","thead","tbody","tr","th","td","img"],ALLOWED_ATTR:["class","href","src","alt","target","rel"]});
 const share=async(k:"facebook"|"linkedin"|"whatsapp"|"copy")=>{try{const {data}=await (supabase as any).rpc("increment_news_share",{p_news_id:article?.id});if(typeof data==="number")setShares(data)}catch{} if(k==="copy"){try{await navigator.clipboard.writeText(url);toast.success("Lien copié")}catch{toast.error("Copie impossible")}}else if(k==="facebook")window.open("https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(url),"_blank","width=600,height=500");else if(k==="linkedin")window.open("https://www.linkedin.com/sharing/share-offsite/?url="+encodeURIComponent(url),"_blank","width=600,height=500");else window.open("https://wa.me/?text="+encodeURIComponent(title+"\n\n"+url),"_blank")};
 if(isLoading)return <div className="min-h-screen grid place-items-center bg-[#111] text-white"><div className="h-8 w-8 animate-spin rounded-full border-2 border-white/20 border-t-[#c99a4a]"/></div>;
 if(!article)return <><Navbar/><NotFound/><Footer/></>;
 return <><Helmet><title>{title} | Actualités — Inocent KOFFI</title><meta name="description" content={excerpt.slice(0,155)}/><link rel="canonical" href={url}/>{arr[0]&&<meta property="og:image" content={arr[0]}/>}</Helmet><ArticleJsonLD type="NewsArticle" headline={title} description={excerpt} image={arr[0]} datePublished={article.published_at||article.created_at} dateModified={article.updated_at||article.published_at||article.created_at} path={"/actualites/"+article.slug} section={article.category||"Actualité"}/><BreadcrumbJsonLd items={[{name:"Actualités",path:"/actualites"},{name:title,path:"/actualites/"+article.slug}]}/>
 <div className="min-h-screen bg-[#f4f1ea] text-[#151515]"><Navbar/><main className="pt-20">
  <section className="relative overflow-hidden bg-[#111] text-white">
   {arr[0]&&<div className="absolute inset-0 opacity-30">{image(arr[0],title,"h-full w-full object-cover blur-sm scale-110")}</div>}<div className="absolute inset-0 bg-gradient-to-t from-[#111] via-[#111]/85 to-[#111]/60"/>
   <div className="relative site-container py-14 sm:py-20 lg:py-28"><div className="content-measure"><Link to="/actualites" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-white/55 hover:text-white"><ArrowLeft className="h-4 w-4"/>Actualités</Link><div className="mt-10 flex flex-wrap gap-3 text-xs text-white/55"><Badge className="border-[#c99a4a]/50 bg-[#c99a4a]/10 text-[#e2b96d]">{article.category||"Actualité"}</Badge><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5"/>{new Date(article.published_at||article.created_at).toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"})}</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{reading(content)} min</span><span className="inline-flex items-center gap-1"><Eye className="h-3.5 w-3.5"/>{view}</span></div><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[.95] sm:text-6xl lg:text-7xl">{title}</h1><p className="mt-7 max-w-4xl text-base leading-7 text-white/70 sm:text-lg">{excerpt}</p><p className="mt-6 text-xs text-white/35">Par {article.author||"Inocent KOFFI"}</p></div></div>
   {arr[0]&&<div className="site-container pb-0"><div className="content-measure overflow-hidden rounded-2xl"><div className="aspect-[16/8]">{image(arr[0],title,"h-full w-full object-cover")}</div></div></div>}
  </section>
  <section className="site-container section-space"><div className="content-measure grid gap-10 lg:grid-cols-[12rem_minmax(0,1fr)] lg:gap-14"><aside className="lg:sticky lg:top-28 lg:self-start"><div className="border-y border-black/10 py-4 text-xs text-black/50"><p className="font-semibold uppercase tracking-widest text-black/35">Publication</p><p className="mt-2">{new Date(article.published_at||article.created_at).toLocaleDateString("fr-FR")}</p><p>{reading(content)} min de lecture</p><p>{shares} partage{shares>1?"s":""}</p></div><div className="mt-4 flex flex-wrap gap-2 lg:flex-col"><Button size="sm" variant="outline" onClick={()=>void share("facebook")}>Facebook</Button><Button size="sm" variant="outline" onClick={()=>void share("linkedin")}>LinkedIn</Button><Button size="sm" variant="outline" onClick={()=>void share("whatsapp")}><MessageCircle className="mr-1.5 h-3.5 w-3.5"/>WhatsApp</Button><Button size="sm" variant="outline" onClick={()=>void share("copy")}><Copy className="mr-1.5 h-3.5 w-3.5"/>Copier</Button></div></aside>
   <article><div className="prose prose-lg max-w-none break-words prose-headings:font-serif prose-headings:text-[#151515] prose-p:text-black/75 prose-p:leading-8 prose-li:text-black/75 prose-strong:text-[#151515] prose-a:text-[#9b7132] prose-blockquote:border-[#c99a4a]">{vids.length>0&&<div className="mb-10 space-y-5">{vids.map((v,i)=><div key={v+i} className="overflow-hidden rounded-2xl bg-black"><video controls preload="metadata" poster={arr[0]} className="aspect-video w-full"><source src={v}/></video><div className="flex items-center gap-2 px-4 py-3 text-xs text-white/55"><Play className="h-3.5 w-3.5"/>Vidéo associée</div></div>)}</div>}<div dangerouslySetInnerHTML={{__html:safe}}/>{arr.length>1&&<div className="mt-12 safe-grid">{arr.slice(1).map((i,n)=><div key={i+n} className="aspect-[4/3] overflow-hidden rounded-xl">{image(i,title+" — image "+(n+2),"h-full w-full object-cover")}</div>)}</div>}</div></article></div></section>
  <section className="border-t border-black/10 bg-white py-14"><div className="site-container"><div className="content-measure"><div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#9b7132]">Continuer</p><h2 className="mt-2 font-serif text-3xl">À lire ensuite</h2></div><Link to="/actualites" className="text-xs font-bold uppercase tracking-widest">Toutes les publications <ArrowRight className="ml-1 inline h-3.5 w-3.5"/></Link></div><Related currentId={article.id}/></div></div></section>
 </main><Footer/></div></>
}

function Related({currentId}:{currentId:string}){
 const {data=[],isLoading}=useQuery({queryKey:["news-related",currentId],queryFn:async()=>{const db=supabase as any;const {data,error}=await db.from("news_relations").select("relevance,relation_reason,related:news!news_relations_related_news_id_fkey(id,slug,title_fr,excerpt_fr,category,featured_image,images,published_at,is_published)").eq("news_id",currentId).order("relevance",{ascending:false}).limit(3);if(error)throw error;return (data||[]).filter((r:any)=>r.related?.is_published!==false).map((r:any)=>r.related)},enabled:!!currentId});
 if(isLoading)return <div className="safe-grid">{[1,2,3].map(i=><div key={i} className="aspect-[16/10] animate-pulse rounded-2xl bg-black/5"/>)}</div>;
 if(!data.length)return <p className="rounded-2xl border bg-black/[.02] p-6 text-sm text-black/50">Aucun article associé.</p>;
 return <div className="safe-grid">{data.map((i:any)=><Link key={i.id} to={"/actualites/"+i.slug} className="group overflow-hidden rounded-2xl border bg-white"><div className="aspect-[16/10] overflow-hidden">{image(media(parseArray(i.images)[0]||i.featured_image),i.title_fr,"h-full w-full object-cover transition duration-700 group-hover:scale-105")}</div><div className="p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-[#9b7132]">{i.category||"Actualité"}</p><h3 className="mt-2 font-serif text-xl leading-tight group-hover:text-[#9b7132]">{i.title_fr}</h3>{i.relation_reason&&<p className="mt-2 text-xs leading-5 text-black/45">{i.relation_reason}</p>}</div></Link>)}</div>;
}
