import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Loader2, LogOut, MessageSquare, RefreshCw, ArrowRight } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { formatFcfa } from "@/hooks/useSiteContent";

type Order={id:string;order_number:string;service_title:string;amount:number;currency:string;status:string;payment_status:string;created_at:string};
type Message={id:string;order_id:string|null;subject:string;message:string;from_admin:boolean;created_at:string};
const statusLabel=(s:string)=>({nouvelle:"Nouvelle",en_discussion:"En discussion",validee:"Validée",en_production:"En production",livree:"Livrée",annulee:"Annulée"} as Record<string,string>)[s]||s;
const paymentLabel=(s:string)=>({en_attente:"En attente",acompte:"Acompte reçu",paye:"Payé",rembourse:"Remboursé"} as Record<string,string>)[s]||s;

export default function ClientPortal(){
 const navigate=useNavigate(); const [loading,setLoading]=useState(true); const [userEmail,setUserEmail]=useState(""); const [orders,setOrders]=useState<Order[]>([]); const [messages,setMessages]=useState<Message[]>([]); const [subject,setSubject]=useState(""); const [message,setMessage]=useState(""); const [selectedOrder,setSelectedOrder]=useState(""); const [sending,setSending]=useState(false);
 const load=async(userId:string)=>{const [o,m]=await Promise.all([(supabase as any).from("service_orders").select("id,order_number,service_title,amount,currency,status,payment_status,created_at").eq("user_id",userId).order("created_at",{ascending:false}),(supabase as any).from("client_messages").select("id,order_id,subject,message,from_admin,created_at").eq("user_id",userId).order("created_at",{ascending:false})]);if(!o.error)setOrders((o.data||[]) as Order[]);if(!m.error)setMessages((m.data||[]) as Message[])};
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){navigate("/login?next=/client",{replace:true});return;}setUserEmail(user.email||"");await load(user.id);setLoading(false)})()},[navigate]);
 const send=async()=>{if(!subject.trim()||!message.trim())return;setSending(true);const {data:{user}}=await supabase.auth.getUser();if(user){const {error}=await (supabase as any).from("client_messages").insert({user_id:user.id,order_id:selectedOrder||null,subject:subject.trim(),message:message.trim(),from_admin:false});if(!error){setSubject("");setMessage("");await load(user.id)}}setSending(false)};
 if(loading)return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin"/></div>;
 return <><Helmet><title>Mon espace client — Inocent KOFFI</title><meta name="robots" content="noindex,nofollow"/></Helmet><Navbar/><main className="min-h-screen bg-secondary/20 pt-24 pb-16"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mb-8 flex flex-col gap-4 rounded-2xl bg-card border p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-accent">Espace client</p><h1 className="mt-2 text-3xl font-bold">Mes commandes & échanges</h1><p className="mt-2 text-sm text-muted-foreground">{userEmail}</p></div><Button variant="outline" onClick={async()=>{await supabase.auth.signOut();navigate("/")}}><LogOut className="mr-2 h-4 w-4"/>Déconnexion</Button></div>
 <div className="grid gap-6 lg:grid-cols-[1.4fr_.9fr]"><section><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Mes commandes</CardTitle><Button size="sm" variant="outline" onClick={async()=>{const {data:{user}}=await supabase.auth.getUser();if(user)await load(user.id)}}><RefreshCw className="mr-2 h-4 w-4"/>Actualiser</Button></CardHeader><CardContent>{!orders.length?<div className="py-10 text-center text-sm text-muted-foreground">Aucune commande associée à ce compte.<div className="mt-4"><Button asChild><Link to="/boutique">Découvrir la boutique<ArrowRight className="ml-2 h-4 w-4"/></Link></Button></div></div>:<div className="space-y-3">{orders.map(o=><article key={o.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{o.service_title}</p><p className="text-xs text-muted-foreground">{o.order_number} · {new Date(o.created_at).toLocaleDateString("fr-FR")}</p></div><Badge>{statusLabel(o.status)}</Badge></div><div className="mt-3 flex flex-wrap gap-3 text-sm"><span>{Number(o.amount)?formatFcfa(Number(o.amount)):"Sur devis"}</span><span className="text-muted-foreground">Paiement : {paymentLabel(o.payment_status)}</span></div></article>)}</div>}</CardContent></Card></section>
 <aside className="space-y-6"><Card><CardHeader><CardTitle>Écrire à l'équipe</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Objet"/><select value={selectedOrder} onChange={e=>setSelectedOrder(e.target.value)} className="w-full rounded-md border bg-background px-3 py-2 text-sm"><option value="">Commande liée (facultatif)</option>{orders.map(o=><option key={o.id} value={o.id}>{o.order_number} — {o.service_title}</option>)}</select><Textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Votre message..." rows={5}/><Button className="w-full" disabled={sending||!subject.trim()||!message.trim()} onClick={()=>void send()}><MessageSquare className="mr-2 h-4 w-4"/>{sending?"Envoi…":"Envoyer le message"}</Button></CardContent></Card>
 <Card><CardHeader><CardTitle>Historique des échanges</CardTitle></CardHeader><CardContent>{!messages.length?<p className="text-sm text-muted-foreground">Aucun message.</p>:<div className="space-y-3 max-h-[420px] overflow-auto">{messages.map(m=><div key={m.id} className={"rounded-xl p-3 "+(m.from_admin?"bg-primary/5":"bg-secondary")}><div className="flex justify-between gap-2"><span className="text-xs font-semibold">{m.from_admin?"AgriCapital":"Vous"}</span><span className="text-[11px] text-muted-foreground">{new Date(m.created_at).toLocaleString("fr-FR")}</span></div><p className="mt-1 text-sm font-medium">{m.subject}</p><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{m.message}</p></div>)}</div>}</CardContent></Card></aside></div></div></main><Footer/></>;
}