export type SiteLanguage = "fr" | "en" | "es" | "de" | "zh" | "ar" | "bci" | "dyu";

export const siteTranslations: Record<SiteLanguage, Record<string, string>> = {
  fr: {
    "nav.home":"Accueil","nav.about":"À propos","nav.expertise":"Expertises","nav.portfolio":"Réalisations","nav.studio":"Studio","nav.shop":"Boutique","nav.news":"Actualités","nav.contact":"Contact","nav.projectCta":"Parler d'un projet",
    "hero.badge1":"Entrepreneur Agro & Digital","hero.badge2":"Développeur web · Praticien IA","hero.location":"Côte d'Ivoire","hero.creator":"Créateur de solutions","hero.value":"Je transforme vos idées en solutions digitales et concrètes.","hero.description":"Sites web, applications, outils métier, intelligence artificielle, contenus vidéo et audio : je conçois des solutions adaptées aux besoins réels des entreprises, organisations et porteurs de projets.","hero.portfolio":"Voir mes réalisations","hero.expertise":"Découvrir mes expertises",
    "news.search":"Rechercher une publication…","news.all":"Toutes","news.featured":"À la une","news.latest":"Dernières publications","news.read":"Lire la publication","news.open":"Ouvrir","news.views":"vues","news.video":"Vidéo","news.loading":"Chargement des actualités…","news.empty":"Aucune publication trouvée.","news.emptyHint":"Modifiez la recherche ou le filtre, ou publiez une nouvelle actualité depuis l'espace éditorial.","news.related":"Articles associés","news.relatedNone":"Aucun article suffisamment proche pour être associé automatiquement.","news.back":"Retour aux actualités","news.copy":"Lien copié","news.share":"Partager",
    "footer.tagline":"Entrepreneur Agro & Digital · Développeur web · Praticien IA · Créateur de solutions. Je transforme vos idées en solutions digitales et concrètes.","footer.otherProject":"Un projet parmi d'autres","footer.agricapitalText":"AgriCapital fait partie de mon parcours entrepreneurial. Pour les informations officielles, les offres et les démarches agricoles, consultez directement le site officiel.","footer.navigation":"Navigation","footer.contact":"Contact","footer.rights":"Tous droits réservés","footer.legal":"Mentions légales"
  },
  en: {
    "nav.home":"Home","nav.about":"About","nav.expertise":"Expertise","nav.portfolio":"Work","nav.studio":"Studio","nav.shop":"Shop","nav.news":"News","nav.contact":"Contact","nav.projectCta":"Discuss a project",
    "hero.badge1":"Agro & Digital Entrepreneur","hero.badge2":"Web Developer · AI Practitioner","hero.location":"Côte d'Ivoire","hero.creator":"Solution Creator","hero.value":"I turn your ideas into practical digital solutions.","hero.description":"Websites, applications, business tools, artificial intelligence, video and audio content: I design solutions adapted to the real needs of companies, organizations and project leaders.","hero.portfolio":"View my work","hero.expertise":"Discover my expertise",
    "news.search":"Search a publication…","news.all":"All","news.featured":"Featured","news.latest":"Latest publications","news.read":"Read publication","news.open":"Open","news.views":"views","news.video":"Video","news.loading":"Loading news…","news.empty":"No publication found.","news.emptyHint":"Change your search or filter, or publish a new news item from the editorial space.","news.related":"Related articles","news.relatedNone":"No sufficiently close article was found for automatic association.","news.back":"Back to news","news.copy":"Link copied","news.share":"Share",
    "footer.tagline":"Agro & Digital Entrepreneur · Web Developer · AI Practitioner · Solution Creator. I turn your ideas into practical digital solutions.","footer.otherProject":"One project among others","footer.agricapitalText":"AgriCapital is part of my entrepreneurial journey. For official information, offers and agricultural procedures, please visit the official website.","footer.navigation":"Navigation","footer.contact":"Contact","footer.rights":"All rights reserved","footer.legal":"Legal notice"
  },
  es: {
    "nav.home":"Inicio","nav.about":"Sobre mí","nav.expertise":"Especialidades","nav.portfolio":"Realizaciones","nav.studio":"Estudio","nav.shop":"Tienda","nav.news":"Actualidades","nav.contact":"Contacto","nav.projectCta":"Hablar de un proyecto",
    "hero.badge1":"Emprendedor Agro & Digital","hero.badge2":"Desarrollador web · Practicante de IA","hero.location":"Côte d'Ivoire","hero.creator":"Creador de soluciones","hero.value":"Transformo tus ideas en soluciones digitales y concretas.","hero.description":"Sitios web, aplicaciones, herramientas profesionales, inteligencia artificial y contenidos de vídeo y audio: diseño soluciones adaptadas a las necesidades reales de empresas, organizaciones y emprendedores.","hero.portfolio":"Ver mis realizaciones","hero.expertise":"Descubrir mis especialidades",
    "news.search":"Buscar una publicación…","news.all":"Todas","news.featured":"Destacada","news.latest":"Últimas publicaciones","news.read":"Leer la publicación","news.open":"Abrir","news.views":"vistas","news.video":"Vídeo","news.loading":"Cargando actualidades…","news.empty":"No se ha encontrado ninguna publicación.","news.emptyHint":"Modifica la búsqueda o el filtro, o publica una nueva actualidad desde el espacio editorial.","news.related":"Artículos relacionados","news.relatedNone":"No se ha encontrado un artículo suficientemente cercano para asociarlo automáticamente.","news.back":"Volver a actualidades","news.copy":"Enlace copiado","news.share":"Compartir",
    "footer.tagline":"Emprendedor Agro & Digital · Desarrollador web · Practicante de IA · Creador de soluciones. Transformo tus ideas en soluciones digitales y concretas.","footer.otherProject":"Un proyecto entre otros","footer.agricapitalText":"AgriCapital forma parte de mi trayectoria empresarial. Para información oficial, ofertas y trámites agrícolas, consulta directamente el sitio oficial.","footer.navigation":"Navegación","footer.contact":"Contacto","footer.rights":"Todos los derechos reservados","footer.legal":"Aviso legal"
  },
  de: {
    "nav.home":"Startseite","nav.about":"Über mich","nav.expertise":"Kompetenzen","nav.portfolio":"Projekte","nav.studio":"Studio","nav.shop":"Shop","nav.news":"Aktuelles","nav.contact":"Kontakt","nav.projectCta":"Über ein Projekt sprechen",
    "hero.badge1":"Agro- & Digitalunternehmer","hero.badge2":"Webentwickler · KI-Praktiker","hero.location":"Côte d'Ivoire","hero.creator":"Lösungsentwickler","hero.value":"Ich verwandle Ihre Ideen in konkrete digitale Lösungen.","hero.description":"Websites, Anwendungen, Geschäftstools, künstliche Intelligenz sowie Video- und Audioinhalte: Ich entwickle Lösungen für die tatsächlichen Bedürfnisse von Unternehmen, Organisationen und Projektträgern.","hero.portfolio":"Meine Projekte ansehen","hero.expertise":"Meine Kompetenzen entdecken",
    "news.search":"Publikation suchen…","news.all":"Alle","news.featured":"Top-Beitrag","news.latest":"Neueste Veröffentlichungen","news.read":"Beitrag lesen","news.open":"Öffnen","news.views":"Aufrufe","news.video":"Video","news.loading":"Aktuelles wird geladen…","news.empty":"Keine Veröffentlichung gefunden.","news.emptyHint":"Ändern Sie Suche oder Filter oder veröffentlichen Sie eine neue Meldung im redaktionellen Bereich.","news.related":"Verwandte Artikel","news.relatedNone":"Kein ausreichend ähnlicher Artikel für die automatische Zuordnung gefunden.","news.back":"Zurück zu Aktuelles","news.copy":"Link kopiert","news.share":"Teilen",
    "footer.tagline":"Agro- & Digitalunternehmer · Webentwickler · KI-Praktiker · Lösungsentwickler. Ich verwandle Ihre Ideen in konkrete digitale Lösungen.","footer.otherProject":"Ein Projekt unter anderen","footer.agricapitalText":"AgriCapital ist Teil meiner unternehmerischen Laufbahn. Für offizielle Informationen, Angebote und landwirtschaftliche Verfahren besuchen Sie bitte die offizielle Website.","footer.navigation":"Navigation","footer.contact":"Kontakt","footer.rights":"Alle Rechte vorbehalten","footer.legal":"Impressum"
  },
  zh: {
    "nav.home":"首页","nav.about":"关于我","nav.expertise":"专业领域","nav.portfolio":"项目成果","nav.studio":"工作室","nav.shop":"商店","nav.news":"新闻","nav.contact":"联系","nav.projectCta":"洽谈项目",
    "hero.badge1":"农业与数字创业者","hero.badge2":"Web开发者 · AI实践者","hero.location":"科特迪瓦","hero.creator":"解决方案创造者","hero.value":"我把您的想法转化为具体的数字解决方案。","hero.description":"网站、应用、业务工具、人工智能以及视频和音频内容：我根据企业、组织和项目负责人的实际需求设计解决方案。","hero.portfolio":"查看我的项目","hero.expertise":"了解我的专业领域",
    "news.search":"搜索文章…","news.all":"全部","news.featured":"精选","news.latest":"最新发布","news.read":"阅读文章","news.open":"打开","news.views":"次浏览","news.video":"视频","news.loading":"正在加载新闻…","news.empty":"未找到文章。","news.emptyHint":"请修改搜索或筛选条件，或从编辑空间发布新的新闻。","news.related":"相关文章","news.relatedNone":"没有找到足够相关的文章来自动关联。","news.back":"返回新闻","news.copy":"链接已复制","news.share":"分享",
    "footer.tagline":"农业与数字创业者 · Web开发者 · AI实践者 · 解决方案创造者。我把您的想法转化为具体的数字解决方案。","footer.otherProject":"众多项目之一","footer.agricapitalText":"AgriCapital是我创业历程中的一个项目。有关官方信息、服务和农业流程，请直接访问官方网站。","footer.navigation":"导航","footer.contact":"联系","footer.rights":"版权所有","footer.legal":"法律声明"
  },
  ar: {
    "nav.home":"الرئيسية","nav.about":"نبذة عني","nav.expertise":"الخبرات","nav.portfolio":"الأعمال","nav.studio":"الاستوديو","nav.shop":"المتجر","nav.news":"الأخبار","nav.contact":"اتصل","nav.projectCta":"تحدث عن مشروع",
    "hero.badge1":"رائد أعمال في الزراعة والتحول الرقمي","hero.badge2":"مطور ويب · ممارس للذكاء الاصطناعي","hero.location":"ساحل العاج","hero.creator":"مبتكر حلول","hero.value":"أحوّل أفكاركم إلى حلول رقمية وعملية.","hero.description":"مواقع وتطبيقات وأدوات أعمال وذكاء اصطناعي ومحتوى مرئي وسمعي: أصمم حلولاً تستجيب للاحتياجات الفعلية للشركات والمنظمات وأصحاب المشاريع.","hero.portfolio":"شاهد أعمالي","hero.expertise":"اكتشف خبراتي",
    "news.search":"البحث عن منشور…","news.all":"الكل","news.featured":"مميز","news.latest":"أحدث المنشورات","news.read":"اقرأ المنشور","news.open":"فتح","news.views":"مشاهدة","news.video":"فيديو","news.loading":"جارٍ تحميل الأخبار…","news.empty":"لم يتم العثور على منشور.","news.emptyHint":"غيّر البحث أو المرشح، أو انشر خبراً جديداً من المساحة التحريرية.","news.related":"مقالات ذات صلة","news.relatedNone":"لم يتم العثور على مقال قريب بما يكفي للربط التلقائي.","news.back":"العودة إلى الأخبار","news.copy":"تم نسخ الرابط","news.share":"مشاركة",
    "footer.tagline":"رائد أعمال في الزراعة والتحول الرقمي · مطور ويب · ممارس للذكاء الاصطناعي · مبتكر حلول. أحوّل أفكاركم إلى حلول رقمية وعملية.","footer.otherProject":"مشروع من بين مشاريع أخرى","footer.agricapitalText":"AgriCapital جزء من مسيرتي الريادية. للمعلومات الرسمية والعروض والإجراءات الزراعية، يرجى زيارة الموقع الرسمي مباشرة.","footer.navigation":"التنقل","footer.contact":"اتصل","footer.rights":"جميع الحقوق محفوظة","footer.legal":"الإشعار القانوني"
  },
  bci: {
    "nav.home":"Awlo","nav.about":"Min su ndɛ","nav.expertise":"Silɛ mun","nav.portfolio":"Junman nga n yo","nav.studio":"Studio","nav.shop":"Nzuɛlɛ","nav.news":"Ndɛ uflɛ mun","nav.contact":"Flɛ min","nav.projectCta":"Koko junman ndɛ",
    "hero.badge1":"Fie junman nin dijital junman bolɛ","hero.badge2":"Web difuɛ · IA silɛfuɛ","hero.location":"Côte d’Ivoire","hero.creator":"Ninnge yofuɛ","hero.value":"N kaci ɔ akunndan mun dijital nin ninnge nga be kwla yo ɔ.","hero.description":"Web bue, aplikasyon, junman su ninnge, IA, video nin audio: n yo atin nga be kɛ junman sua, sua mun nin junman yofuɛ mun ninnge su.","hero.portfolio":"Nian n junman nga n yo","hero.expertise":"Nian n silɛ mun",
    "news.search":"Kɛ ndɛ wie yɛ ɔ kunndɛ…","news.all":"Kwlaa","news.featured":"Ndɛ dandan","news.latest":"Ndɛ uflɛ mun","news.read":"Kanngan ndɛ’n","news.open":"Bue","news.views":"nianlɛ","news.video":"Video","news.loading":"Ndɛ mun bɛ kɔ…","news.empty":"Ndɛ si nunman.","news.emptyHint":"Kaci ɔ kunndɛlɛ annzɛ ɔ siesielɛ, annzɛ klɛ ndɛ uflɛ nun junman su.","news.related":"Ndɛ nga be nin i sɛ","news.relatedNone":"Ndɛ kɛ kun fi i sɛ nin i nunman lɛ kɛ be kɛ i sɛ.","news.back":"Sa sin ndɛ mun su","news.copy":"Lien klɛli","news.share":"Fa kle",
    "footer.tagline":"Fie junman nin dijital junman bolɛ · Web difuɛ · IA silɛfuɛ · Ninnge yofuɛ. N kaci ɔ akunndan mun dijital nin ninnge nga be kwla yo ɔ.","footer.otherProject":"Junman kun nga n yo junman kwlaa nun","footer.agricapitalText":"AgriCapital yɛ junman kun n ka junman ajalɛ nun. Ndɛ tititi, nzuɛlɛ nin fie junman ndɛ, kɔ site tititi su.","footer.navigation":"Atin","footer.contact":"Flɛ min","footer.rights":"Atin kwlaa ti be liɛ","footer.legal":"Mmla ndɛ mun"
  },
  dyu: {
    "nav.home":"So kɔnɔ","nav.about":"Ne kan","nav.expertise":"Dɔnniya","nav.portfolio":"Baara minnu kɛra","nav.studio":"Studio","nav.shop":"Feereli","nav.news":"Kunnafoni kuraw","nav.contact":"Ne weele","nav.projectCta":"An ka baro baara kan",
    "hero.badge1":"Sɛnɛ ni dijitali baarakɛla","hero.badge2":"Web difuɛ · IA baarakɛla","hero.location":"Kotidiwari","hero.creator":"Sira kuraw yɔrɔ yɔrɔ yɔrɔ","hero.value":"N bɛ i ka hakilinataw kɛ dijitali ni baara tiɲɛna ye.","hero.description":"Websites, aplikasyonw, baara minɛnw, IA, video ni audio: n bɛ sira labɛn min bɛ baaradenw, jɛkulu baw ani baara daminɛlaw ka koow jaabi.","hero.portfolio":"N ka baaraw lajɛ","hero.expertise":"N ka dɔnniya lajɛ",
    "news.search":"Kunnafoni ɲinini…","news.all":"Bɛɛ","news.featured":"Kunnafoni ɲuman","news.latest":"Kunnafoni kura","news.read":"Kunnafoni kalan","news.open":"Ouvrir","news.views":"lajɛli","news.video":"Video","news.loading":"Kunnafoni bɛ don…","news.empty":"Kunnafoni si ma sɔrɔ.","news.emptyHint":"A ka ɲinini walima filɛli yèlèma, walima kunnafoni kura ci sɛbɛnni yɔrɔ la.","news.related":"Sɛbɛn minnu bɛ jɛ","news.relatedNone":"Sɛbɛn minɛ bɛɛ ka kan ka jɛ, o ma sɔrɔ.","news.back":"Ka segin kunnafoniw ma","news.copy":"Lien nɔrɔli kɛra","news.share":"Yɛrɛ fɔ",
    "footer.tagline":"Sɛnɛ ni dijitali baarakɛla · Web difuɛ · IA baarakɛla · Sira kuraw yɔrɔ. N bɛ i ka hakilinataw kɛ dijitali ni baara tiɲɛna ye.","footer.otherProject":"Baara kelen ka fara baara wɛrɛw kan","footer.agricapitalText":"AgriCapital ye n ka baara daminɛ sira kɔnɔ baara kelen ye. Kunnakofoniya, feereli ni sɛnɛ koow kama, site officiel lajɛ.","footer.navigation":"Sira","footer.contact":"Ne weele","footer.rights":"Dɛmɛ bɛɛ bɛ marali","footer.legal":"Sariya kunnafoni"
  }
};

// Compatibility keys used by older page components. They now follow the personal-site positioning.
Object.assign(siteTranslations.fr, {
  "nav.vision":"Vision", "nav.agricapital":"AgriCapital", "nav.projects":"Réalisations", "nav.partnership":"Partenariats", "nav.blog":"Actualités", "nav.gallery":"Studio",
  "hero.badge":"Entrepreneur Agro & Digital", "hero.title":"Inocent KOFFI", "hero.subtitle":"Développeur web · Praticien IA · Créateur de solutions", "hero.description":"Je transforme vos idées en solutions digitales et concrètes."
});
Object.assign(siteTranslations.en, {
  "nav.vision":"Vision", "nav.agricapital":"AgriCapital", "nav.projects":"Work", "nav.partnership":"Partnerships", "nav.blog":"News", "nav.gallery":"Studio",
  "hero.badge":"Agro & Digital Entrepreneur", "hero.title":"Inocent KOFFI", "hero.subtitle":"Web Developer · AI Practitioner · Solution Creator", "hero.description":"I turn your ideas into practical digital solutions."
});
Object.assign(siteTranslations.es, {
  "nav.vision":"Visión", "nav.agricapital":"AgriCapital", "nav.projects":"Realizaciones", "nav.partnership":"Alianzas", "nav.blog":"Actualidades", "nav.gallery":"Estudio",
  "hero.badge":"Emprendedor Agro & Digital", "hero.title":"Inocent KOFFI", "hero.subtitle":"Desarrollador web · Practicante de IA · Creador de soluciones", "hero.description":"Transformo tus ideas en soluciones digitales y concretas."
});
Object.assign(siteTranslations.de, {
  "nav.vision":"Vision", "nav.agricapital":"AgriCapital", "nav.projects":"Projekte", "nav.partnership":"Partnerschaften", "nav.blog":"Aktuelles", "nav.gallery":"Studio",
  "hero.badge":"Agro- & Digitalunternehmer", "hero.title":"Inocent KOFFI", "hero.subtitle":"Webentwickler · KI-Praktiker · Lösungsentwickler", "hero.description":"Ich verwandle Ihre Ideen in konkrete digitale Lösungen."
});
Object.assign(siteTranslations.zh, {
  "nav.vision":"愿景", "nav.agricapital":"AgriCapital", "nav.projects":"项目成果", "nav.partnership":"合作伙伴", "nav.blog":"新闻", "nav.gallery":"工作室",
  "hero.badge":"农业与数字创业者", "hero.title":"Inocent KOFFI", "hero.subtitle":"Web开发者 · AI实践者 · 解决方案创造者", "hero.description":"我把您的想法转化为具体的数字解决方案。"
});
Object.assign(siteTranslations.ar, {
  "nav.vision":"الرؤية", "nav.agricapital":"AgriCapital", "nav.projects":"الأعمال", "nav.partnership":"الشراكات", "nav.blog":"الأخبار", "nav.gallery":"الاستوديو",
  "hero.badge":"رائد أعمال في الزراعة والتحول الرقمي", "hero.title":"Inocent KOFFI", "hero.subtitle":"مطور ويب · ممارس للذكاء الاصطناعي · مبتكر حلول", "hero.description":"أحوّل أفكاركم إلى حلول رقمية وعملية."
});
Object.assign(siteTranslations.bci, {
  "nav.vision":"Akunndan", "nav.agricapital":"AgriCapital", "nav.projects":"Junman nga n yo", "nav.partnership":"Jɛlɛlɛ", "nav.blog":"Ndɛ uflɛ mun", "nav.gallery":"Studio",
  "hero.badge":"Fie junman nin dijital junman bolɛ", "hero.title":"Inocent KOFFI", "hero.subtitle":"Web difuɛ · IA silɛfuɛ · Ninnge yofuɛ", "hero.description":"N kaci ɔ akunndan mun dijital nin ninnge nga be kwla yo ɔ."
});
Object.assign(siteTranslations.dyu, {
  "nav.vision":"Lajɛya", "nav.agricapital":"AgriCapital", "nav.projects":"Baara minnu kɛra", "nav.partnership":"Jɛkuluya", "nav.blog":"Kunnafoni kuraw", "nav.gallery":"Studio",
  "hero.badge":"Sɛnɛ ni dijitali baarakɛla", "hero.title":"Inocent KOFFI", "hero.subtitle":"Web difuɛ · IA baarakɛla · Sira kuraw yɔrɔ", "hero.description":"N bɛ i ka hakilinataw kɛ dijitali ni baara tiɲɛna ye."
});
